server:
  name: go-subscription
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

mongo:
  uri: mongodb+srv://dbUser:Demoaccount1@projectdemo.g0lah.mongodb.net
  database: masterdata

retry:
  retry_count_name: retry
  limit_retry: 3
  goroutines: false
  key: key

handler:
  key: key
  goroutines: true
  retry:
    1: 5
    2: 7
    3: 9

consumer:
  brokers: tricycle-01.srvs.cloudkafka.com:9094
  client:
    username: ah1t9hk0
    password: QvMB75cxJ48KYRnGfwXcRNxzALyAeb7-
  group_id: my-group
  topic: ah1t9hk0-default
